name: Build, Quality, Test

on:
    push:
        branches:
            - '*' # matches every branch that doesn't contain a '/'
            - '*/*' # matches every branch containing a single '/'
            - '**' # matches every branch

jobs:
    default:
        container:
            image: node:19.1.0
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install

            - name: Run prettier
              run: npm run prettier
